export default [
  {
    certificateTitle: `Bachelor's in Engineering, Information & Technology`,
    certificationAuthority: `Helsinki Metropolia University of Applied Sciences`,
    startYear: '2016',
    finishYear: '2020',
    hasCertificate: false,
    certificateLink: null,
    imgSrc: '/images/metropolia.png',
    imgAlt: 'Logo of Metropolia University of applied sciences',
  },
  {
    certificateTitle: `Full Stack Software Developer`,
    certificationAuthority: `Department of Computer Science, University of Helsinki`,
    startYear: null,
    finishYear: null,
    hasCertificate: true,
    certificateLink: `https://studies.cs.helsinki.fi/stats/api/certificate/fullstackopen/en/6ff8e11c1ddd0c1e4618ba3fc0de7a40`,
    imgSrc: '/images/helsinki-uni.png',
    imgAlt: 'Logo of University of Helsinki',
  },
  {
    certificateTitle: `Javascript Algorithms and Data Structures`,
    certificationAuthority: `FreeCodeCamp`,
    startYear: null,
    finishYear: null,
    hasCertificate: true,
    certificateLink: `https://www.freecodecamp.org/certification/acharyasagar/javascript-algorithms-and-data-structures`,
    imgSrc: '/images/freecodecamp.png',
    imgAlt: 'Logo of FreeCodeCamp',
  },
]
